version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      commit-message:
          prefix: 'chore(deps)'
      labels:
          - 'dependencies'
          - 'auto-merge'

    - package-ecosystem: 'npm'
      directory: '/apps/desktop'
      schedule:
          interval: 'daily'
      commit-message:
          prefix: 'chore(deps)'
      labels:
          - 'dependencies'
          - 'auto-merge'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      commit-message:
          prefix: 'chore(actions)'
      labels:
          - 'dependencies'
