name: Notify

on:
    push:
        branches:
            - main
            - develop
    pull_request_target:
        types: [opened, reopened, closed]
    issues:
        types: [opened, closed, reopened]

env:
    NODE_VERSION: 20

    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    GITHUB_ACTOR: ${{ github.actor }}
    GITHUB_EVENT_NAME: ${{ github.event_name }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_REF: ${{ github.ref }}
    GITHUB_SHA: ${{ github.sha }}
    GITHUB_EVENT_PATH: ${{ github.event_path }}

jobs:
    telegram:
        name: Telegram Notification
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Send Telegram notification
              run: node .github/scripts/telegram-notify.js
